export interface FlightSegment {
  airline: string;
  flightNumber: string;
  departureAirportCode: string;
  arrivalAirportCode: string;
  departureDateTime: string;
  arrivalDateTime: string;
  durationMinutes?: number;
  aircraftType?: string;
  terminal?: { departure: string | null; arrival: string | null };
  gate?: { departure: string | null; arrival: string | null };
  cost?: number;
  numberOfTickets?: number;
  costType?: 'per-ticket' | 'total';
  carryOn?: boolean;
  checkedBag?: boolean;
  bookingNumber?: string;
  bookingAgency?: string;
}

export interface HotelBooking {
  placeId: string;
  name: string;
  address: string;
  checkIn: string;
  checkOut: string;
  nights: number;
  cost?: number;
  rating?: number | null;
  distanceFromAirport?: string;
  travelTimeFromAirport?: string;
  includesMeals?: boolean;
  mealPlan?: 'breakfast' | 'half-board' | 'all-inclusive';
  numberOfRooms?: number;
  reservationNames?: string[]; // Array of names for each room
  bookedFrom?: string;
  arrivalTime?: string; // Time of arrival at hotel (HH:MM format)
}

export interface RideLeg {
  type?: 'taxi' | 'rental';
  pickup: string;
  dropoff: string;
  pickupPlaceId?: string;
  dropoffPlaceId?: string;
  distance?: string;
  duration?: string;
  mode?: string;
  date?: string;
  time?: string;
  dateTime?: string;
  cost?: number;
  // Taxi/Ride specific
  notes?: string;
  // Car Rental specific
  voucherNumber?: string;
  rentalCompany?: string;
  pickupDate?: string;
  pickupTime?: string;
  returnDate?: string;
  returnTime?: string;
}

export interface AttractionVisit {
  placeId: string;
  name: string;
  address: string;
  scheduledDate: string;
  scheduledTime?: string;
  rating?: number | null;
  website?: string;
  cost?: number;
  numberOfTickets?: number;
  costType?: 'per-ticket' | 'total';
  attractionType?:
    | 'restaurant'
    | 'park'
    | 'show'
    | 'museum'
    | 'event'
    | 'theme-park'
    | 'water-park'
    | 'custom';
  customType?: string;
}

export interface MealActivity {
  type: 'breakfast' | 'lunch' | 'dinner';
  hotelName: string;
  hotelAddress: string;
  date: string;
  time: string;
  isAutoGenerated: boolean;
}

export interface SharedUser {
  userId: string;
  email: string;
  name: string;
  sharedAt: string;
}

export interface ChecklistItem {
  id: string;
  label: string;
  checked: boolean;
  isCustom?: boolean;
}

export interface ChecklistCategory {
  id: string;
  name: string;
  items: ChecklistItem[];
}

export interface UserChecklist {
  userId: string;
  checklist: ChecklistCategory[];
}

export interface Trip {
  id: string;
  name: string;
  destinations: string[];
  startDate: string;
  endDate: string;
  flights: FlightSegment[];
  hotels: HotelBooking[];
  rides: RideLeg[];
  attractions: AttractionVisit[];
  checklist?: ChecklistCategory[]; // Legacy: owner's checklist (kept for backward compatibility)
  userChecklists?: UserChecklist[]; // New: per-user checklists for shared trips
  createdAt?: string;
  updatedAt?: string;
  userId?: string;
  userEmail?: string;
  sharedWith?: SharedUser[];
  isOwner?: boolean;
  isShared?: boolean;
}

export interface DayBucket {
  date: string;
  flights: FlightSegment[];
  hotels: HotelBooking[];
  rides: RideLeg[];
  attractions: AttractionVisit[];
  meals: MealActivity[];
}

export function groupTripByDay(trip: Trip): DayBucket[] {
  const dayMap: Record<string, DayBucket> = {};
  const range = dateRange(trip.startDate, trip.endDate);
  range.forEach(
    (d) =>
      (dayMap[d] = {
        date: d,
        flights: [],
        hotels: [],
        rides: [],
        attractions: [],
        meals: [],
      })
  );

  const add = (date: string, kind: keyof DayBucket, item: any) => {
    if (!dayMap[date])
      dayMap[date] = {
        date,
        flights: [],
        hotels: [],
        rides: [],
        attractions: [],
        meals: [],
      };
    (dayMap[date][kind] as any[]).push(item);
  };

  trip.flights.forEach((f) =>
    add(f.departureDateTime.slice(0, 10), 'flights', f)
  );
  trip.hotels.forEach((h) => add(h.checkIn.slice(0, 10), 'hotels', h));
  trip.rides.forEach((r) => {
    const rideDate = r.date || r.dateTime?.slice(0, 10) || r.pickupDate;
    if (rideDate) add(rideDate, 'rides', r);
  });
  trip.attractions.forEach((a) => add(a.scheduledDate, 'attractions', a));

  // Generate meal activities based on hotel meal plans
  trip.hotels.forEach((hotel) => {
    if (hotel.includesMeals && hotel.mealPlan) {
      const stayDates = dateRange(
        hotel.checkIn.slice(0, 10),
        hotel.checkOut.slice(0, 10)
      );

      stayDates.forEach((date, index) => {
        const isCheckInDay = index === 0;
        const isCheckOutDay = index === stayDates.length - 1;

        // Generate meals based on meal plan
        if (
          hotel.mealPlan === 'breakfast' ||
          hotel.mealPlan === 'half-board' ||
          hotel.mealPlan === 'all-inclusive'
        ) {
          // Breakfast - SKIP on check-in day (arriving), INCLUDE on checkout day
          if (!isCheckInDay) {
            add(date, 'meals', {
              type: 'breakfast',
              hotelName: hotel.name,
              hotelAddress: hotel.address,
              date: date,
              time: '08:00',
              isAutoGenerated: true,
            } as MealActivity);
          }
        }

        if (hotel.mealPlan === 'all-inclusive') {
          // Lunch - skip on check-in and checkout days
          if (!isCheckInDay && !isCheckOutDay) {
            add(date, 'meals', {
              type: 'lunch',
              hotelName: hotel.name,
              hotelAddress: hotel.address,
              date: date,
              time: '13:00',
              isAutoGenerated: true,
            } as MealActivity);
          }
        }

        if (
          hotel.mealPlan === 'half-board' ||
          hotel.mealPlan === 'all-inclusive'
        ) {
          // Dinner - skip on checkout day (leaving), include on check-in and other days
          if (!isCheckOutDay) {
            add(date, 'meals', {
              type: 'dinner',
              hotelName: hotel.name,
              hotelAddress: hotel.address,
              date: date,
              time: '19:00',
              isAutoGenerated: true,
            } as MealActivity);
          }
        }
      });
    }
  });

  return Object.values(dayMap).sort((a, b) => a.date.localeCompare(b.date));
}

export function dateRange(start: string, end: string): string[] {
  const result: string[] = [];
  // Parse dates as local dates to avoid timezone issues
  const [startY, startM, startD] = start.split('-').map(Number);
  const [endY, endM, endD] = end.split('-').map(Number);
  const cur = new Date(startY, startM - 1, startD);
  const endDate = new Date(endY, endM - 1, endD);

  while (cur <= endDate) {
    const year = cur.getFullYear();
    const month = String(cur.getMonth() + 1).padStart(2, '0');
    const day = String(cur.getDate()).padStart(2, '0');
    result.push(`${year}-${month}-${day}`);
    cur.setDate(cur.getDate() + 1);
  }
  return result;
}
